In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
df = pd.read_csv("./Original csv/spotify_2015_2025_85k.csv")
df

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,234194,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,375706,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,289191,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,209484,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,127435,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84995,TRK-462F0DB0EB74,Address fire large,Hannah Powers,Condition all,2022-08-13,Indie,197426,36,0.33,0.06,7,-9.58,0,0.264,189.94,1000,United Kingdom,0,Universal Music
84996,TRK-7AB4B28EC4C4,Agent section road individual certain,Kylie Lopez,Take,2020-07-14,Hip-Hop,100063,33,0.98,0.83,0,-37.26,0,0.799,122.09,1000,Japan,0,XL Recordings
84997,TRK-4E7FAE07FBEC,Attention,John Frederick,Officer,2025-12-13,Indie,122086,56,0.33,0.74,9,-7.89,1,0.570,193.04,1000,Canada,0,EMI
84998,TRK-F86B054551B6,You act century,Alyssa Foster,Test white,2024-11-20,Hip-Hop,251322,44,0.15,0.09,1,-46.91,0,0.789,139.33,2000,Japan,0,Columbia
84999,TRK-1AFF404AA899,Republican focus,Diana Miller,Product national,2017-12-11,Hip-Hop,100610,42,0.30,0.23,7,-12.22,0,0.712,136.49,2000,Canada,0,Island Records

In [20]:
print((df['track_name'] == 'None').sum())

21

In [21]:
# drop all the rows with "None" as track name
df = df[df['track_name'] != 'None'].copy()

# parse string to datetime
df['release_date'] = pd.to_datetime(df['release_date'])

# convert ms to sec and mins
df['duration_sec'] = df['duration_ms'] / 1000
df['duration_min'] = df['duration_ms'] / 60000

# convert mode and explicit to boolean
df['explicit'] = df['explicit'].astype(bool)
df['mode'] = df['mode'].map({0: 'minor', 1: 'major'})

# looks like minimum stream count is 1000, setting flag to take into account
df['low_stream_flag'] = df['stream_count'] == 1000

df

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,...,mode,instrumentalness,tempo,stream_count,country,explicit,label,duration_sec,duration_min,low_stream_flag
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,234194,55,0.15,0.74,...,minor,0.436,73.12,13000,Brazil,False,Universal Music,234.194,3.903233,False
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,375706,45,0.44,0.46,...,minor,0.223,157.74,1000,France,True,Island Records,375.706,6.261767,True
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,289191,55,0.62,0.80,...,major,0.584,71.03,1000,Germany,True,XL Recordings,289.191,4.819850,True
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,209484,51,0.78,0.98,...,major,0.684,149.00,1000,France,False,Warner Music,209.484,3.491400,True
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,127435,39,0.74,0.18,...,minor,0.304,155.85,2000,United States,False,Independent,127.435,2.123917,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84995,TRK-462F0DB0EB74,Address fire large,Hannah Powers,Condition all,2022-08-13,Indie,197426,36,0.33,0.06,...,minor,0.264,189.94,1000,United Kingdom,False,Universal Music,197.426,3.290433,True
84996,TRK-7AB4B28EC4C4,Agent section road individual certain,Kylie Lopez,Take,2020-07-14,Hip-Hop,100063,33,0.98,0.83,...,minor,0.799,122.09,1000,Japan,False,XL Recordings,100.063,1.667717,True
84997,TRK-4E7FAE07FBEC,Attention,John Frederick,Officer,2025-12-13,Indie,122086,56,0.33,0.74,...,major,0.570,193.04,1000,Canada,False,EMI,122.086,2.034767,True
84998,TRK-F86B054551B6,You act century,Alyssa Foster,Test white,2024-11-20,Hip-Hop,251322,44,0.15,0.09,...,minor,0.789,139.33,2000,Japan,False,Columbia,251.322,4.188700,False
84999,TRK-1AFF404AA899,Republican focus,Diana Miller,Product national,2017-12-11,Hip-Hop,100610,42,0.30,0.23,...,minor,0.712,136.49,2000,Canada,False,Island Records,100.610,1.676833,False

In [22]:
df.to_csv('spotify_cleaned.csv', index=False)