In [29]:
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
df = pd.read_csv("./Original csv/spotify_dataset_gigasheet.csv")
df

,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,Title,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon
0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,-6.679,0.1770,0.008360,0.002330,...,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221,6220896,169907,True,True,1040234854,1.150082,Spotify
1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,-5.815,0.0302,0.086900,0.000687,...,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645,1079128,31003,True,True,310083733,15.183585,Spotify
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,-3.930,0.0522,0.042500,0.046900,...,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055,282142,7399,True,True,63063467,7.956897,Spotify
3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,-5.810,0.0260,0.000015,0.509000,...,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952,1788577,55229,True,True,434663559,11.546875,Spotify
4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,-8.627,0.1710,0.025300,0.000000,...,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958,6197318,155930,True,True,617259738,9.942693,Youtube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20589,SICK LEGEND,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,0.582,0.926,-6.344,0.0328,0.448000,0.000000,...,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678,1113,0,True,True,9227144,11.036949,Spotify
20590,SICK LEGEND,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,0.531,0.936,-1.786,0.1370,0.028000,0.000000,...,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741,2019,0,True,True,10898176,10.140845,Spotify
20591,SICK LEGEND,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,0.443,0.830,-4.679,0.0647,0.024300,0.000000,...,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646,329,0,True,True,6226110,5.389610,Spotify
20592,SICK LEGEND,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,0.417,0.767,-4.004,0.4190,0.356000,0.018400,...,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533,88,0,True,True,6873961,7.101852,Spotify
20593,SICK LEGEND,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,0.498,0.938,-4.543,0.1070,0.002770,0.911000,...,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697,2484,0,True,True,5695584,6.897059,Spotify

In [31]:
print((df['Title'] == 'None').sum())
df.isna().sum()

0

Artist              0
Track               0
Album               0
Album_type          0
Danceability        0
Energy              0
Loudness            0
Speechiness         0
Acousticness        0
Instrumentalness    0
Liveness            0
Valence             0
Tempo               0
Duration_min        0
Title               0
Channel             0
Views               0
Likes               0
Comments            0
Licensed            0
official_video      0
Stream              0
EnergyLiveness      0
most_playedon       0
dtype: int64

In [33]:
df['Album_type'].value_counts()

album          14834
single          4973
compilation      787
Name: Album_type, dtype: int64

In [34]:
#remove compilations
df = df[(df['Album_type'] != "compilation")].copy()

In [35]:
df['Duration_min'].sort_values()

11824     0.000000
13773     0.000000
11860     0.516417
20530     0.516667
20524     0.516667
           ...
5814     16.390533
5359     23.799650
5361     24.737667
4427     55.677867
9311     68.670967
Name: Duration_min, Length: 19807, dtype: float64

In [36]:
# remove tracks longer than 10 mins
df = df[(df['Duration_min'] < 10)].copy()

In [38]:
df = df.sort_values('Stream', ascending=False)
df.duplicated(subset=['Artist', 'Track']).value_counts()

False    19693
True        55
dtype: int64

In [39]:
# remove duplicate artist/track combos
df = df.drop_duplicates(subset=['Artist', 'Track'], keep='first')

In [40]:
numerical_cols = df.select_dtypes(include='number').columns
zero_counts = (df[numerical_cols] == 0).sum()
print(zero_counts)

Danceability          18
Energy                 2
Loudness               2
Speechiness           18
Acousticness           2
Instrumentalness    8985
Liveness               2
Valence               27
Tempo                 18
Duration_min           2
Views                448
Likes                531
Comments             984
Stream               517
EnergyLiveness         2
dtype: int64

In [41]:
#remove rows with zero tempo and duration
df = df[(df['Tempo'] != 0) & (df['Duration_min'] != 0)].copy()

# set flag for zero views and streams
df['zero_engagement_flag'] = (df['Views'] == 0) | (df['Stream'] == 0)
df

,Artist,Track,Album,Album_type,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,Channel,Views,Likes,Comments,Licensed,official_video,Stream,EnergyLiveness,most_playedon,zero_engagement_flag
15166,The Weeknd,Blinding Lights,After Hours,album,0.514,0.730,-5.934,0.0598,0.00146,0.000095,...,TheWeekndVEVO,674164500,8817927,282589,True,True,3386520288,8.138239,Spotify,False
12385,Ed Sheeran,Shape of You,÷ (Deluxe),album,0.825,0.652,-3.183,0.0802,0.58100,0.000000,...,Ed Sheeran,5908398479,31047780,1130327,True,True,3362005201,7.003222,Youtube,False
19082,Lewis Capaldi,Someone You Loved,Divinely Uninspired To A Hellish Extent,album,0.501,0.405,-5.679,0.0319,0.75100,0.000000,...,LewisCapaldiVEVO,586768373,7367091,147565,True,True,2634013335,3.857143,Spotify,False
17847,Post Malone,rockstar (feat. 21 Savage),beerbongs & bentleys,album,0.585,0.520,-6.136,0.0712,0.12400,0.000070,...,PostMaloneVEVO,1060220169,12564657,366520,True,True,2594926619,3.969466,Spotify,False
17356,Swae Lee,Sunflower - Spider-Man: Into the Spider-Verse,Hollywood's Bleeding,album,0.755,0.522,-4.368,0.0575,0.53300,0.000000,...,PostMaloneVEVO,1977389027,13749806,331064,True,True,2538329799,7.620438,Spotify,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15736,JP Cooper,Runaway,Runaway,single,0.617,0.756,-5.812,0.1050,0.21300,0.000000,...,R3HAB,3095821,45919,617,True,True,0,4.941176,Youtube,True
13333,Peter Groeger,Kapitel 1.3 - Der Kaiser von Dallas,Der Kaiser von Dallas (Die einzige Wahrheit üb...,album,0.615,0.193,-22.592,0.9370,0.92900,0.000000,...,Benjamin Quabeck - Topic,21,0,0,True,True,0,1.078212,Youtube,True
1706,Charlie Brown Jr.,Pontes Indestrutiveis - Ao Vivo,Ritmo Ritual E Responsa Ao Vivo,album,0.713,0.653,-11.633,0.1030,0.25100,0.000000,...,charliebrownjrVEVO,5870884,23131,408,True,True,0,1.106780,Youtube,True
6558,Martin Solveig,Hello (feat. Dragonette),Hello,single,0.666,0.975,-3.470,0.0345,0.01350,0.000925,...,Kontor.TV,105623204,635050,25645,True,True,0,9.285714,Youtube,True
2935,Conjunto Primavera,Algo De Mí,Algo De Mi,album,0.651,0.807,-2.437,0.0327,0.45700,0.000000,...,ConjuntoPrimavraVEVO,64374531,176912,4931,True,True,0,3.771028,Youtube,True

In [42]:
df.to_csv('spotify_cleaned.csv', index=False)